//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.28 at 10:41:44 AM MESZ 
//


package de.thorstenberger.taskmodel.complex.complextaskdef;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://complex.taskmodel.thorstenberger.de/complexTaskDef}SubTaskDefType">
 *       &lt;sequence>
 *         &lt;element name="Memento" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="textFieldWidth" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="textFieldHeight" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="taskType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "memento"
})
@XmlRootElement(name = "addonSubTaskDef")
public class AddonSubTaskDef
    extends SubTaskDefType
{

    @XmlAnyElement
    protected Element memento;
    @XmlAttribute
    protected Integer textFieldWidth;
    @XmlAttribute
    protected Integer textFieldHeight;
    @XmlAttribute(required = true)
    protected String taskType;

    /**
     * Gets the value of the memento property.
     * 
     * @return
     *     possible object is
     *     {@link Element }
     *     
     */
    public Element getMemento() {
        return memento;
    }

    /**
     * Sets the value of the memento property.
     * 
     * @param value
     *     allowed object is
     *     {@link Element }
     *     
     */
    public void setMemento(Element value) {
        this.memento = value;
    }

    /**
     * Gets the value of the textFieldWidth property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTextFieldWidth() {
        return textFieldWidth;
    }

    /**
     * Sets the value of the textFieldWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTextFieldWidth(Integer value) {
        this.textFieldWidth = value;
    }

    /**
     * Gets the value of the textFieldHeight property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTextFieldHeight() {
        return textFieldHeight;
    }

    /**
     * Sets the value of the textFieldHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTextFieldHeight(Integer value) {
        this.textFieldHeight = value;
    }

    /**
     * Gets the value of the taskType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaskType() {
        return taskType;
    }

    /**
     * Sets the value of the taskType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaskType(String value) {
        this.taskType = value;
    }

}
