//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.28 at 10:41:44 AM MESZ 
//


package de.thorstenberger.taskmodel.complex.complextaskdef;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://complex.taskmodel.thorstenberger.de/complexTaskDef}SubTaskDefType">
 *       &lt;choice>
 *         &lt;element name="cloze">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="gap">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="correct" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="inputLength">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                                 &lt;minInclusive value="1"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="ignoreCase" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                           &lt;attribute name="initialValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="graphicalCloze">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="backgroundImageBase64" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="gap" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="correct" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="inputLength">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                                 &lt;minInclusive value="1"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="ignoreCase" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                           &lt;attribute name="posX" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="posY" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="initialValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cloze",
    "graphicalCloze"
})
@XmlRootElement(name = "clozeSubTaskDef")
public class ClozeSubTaskDef
    extends SubTaskDefType
{

    protected ClozeSubTaskDef.Cloze cloze;
    protected ClozeSubTaskDef.GraphicalCloze graphicalCloze;

    /**
     * Gets the value of the cloze property.
     * 
     * @return
     *     possible object is
     *     {@link ClozeSubTaskDef.Cloze }
     *     
     */
    public ClozeSubTaskDef.Cloze getCloze() {
        return cloze;
    }

    /**
     * Sets the value of the cloze property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClozeSubTaskDef.Cloze }
     *     
     */
    public void setCloze(ClozeSubTaskDef.Cloze value) {
        this.cloze = value;
    }

    /**
     * Gets the value of the graphicalCloze property.
     * 
     * @return
     *     possible object is
     *     {@link ClozeSubTaskDef.GraphicalCloze }
     *     
     */
    public ClozeSubTaskDef.GraphicalCloze getGraphicalCloze() {
        return graphicalCloze;
    }

    /**
     * Sets the value of the graphicalCloze property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClozeSubTaskDef.GraphicalCloze }
     *     
     */
    public void setGraphicalCloze(ClozeSubTaskDef.GraphicalCloze value) {
        this.graphicalCloze = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="gap">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="correct" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="inputLength">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *                       &lt;minInclusive value="1"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="ignoreCase" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                 &lt;attribute name="initialValue" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "textOrGap"
    })
    public static class Cloze {

        @XmlElements({
            @XmlElement(name = "gap", type = ClozeSubTaskDef.Cloze.Gap.class),
            @XmlElement(name = "text", type = String.class)
        })
        protected List<Object> textOrGap;

        /**
         * Gets the value of the textOrGap property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the textOrGap property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTextOrGap().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ClozeSubTaskDef.Cloze.Gap }
         * {@link String }
         * 
         * 
         */
        public List<Object> getTextOrGap() {
            if (textOrGap == null) {
                textOrGap = new ArrayList<Object>();
            }
            return this.textOrGap;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="correct" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *       &lt;attribute name="inputLength">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
         *             &lt;minInclusive value="1"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="ignoreCase" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *       &lt;attribute name="initialValue" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "correct"
        })
        public static class Gap {

            @XmlElement(required = true)
            protected List<String> correct;
            @XmlAttribute
            protected Integer inputLength;
            @XmlAttribute
            protected Boolean ignoreCase;
            @XmlAttribute
            protected String initialValue;

            /**
             * Gets the value of the correct property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the correct property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCorrect().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getCorrect() {
                if (correct == null) {
                    correct = new ArrayList<String>();
                }
                return this.correct;
            }

            /**
             * Gets the value of the inputLength property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getInputLength() {
                return inputLength;
            }

            /**
             * Sets the value of the inputLength property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setInputLength(Integer value) {
                this.inputLength = value;
            }

            /**
             * Gets the value of the ignoreCase property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isIgnoreCase() {
                return ignoreCase;
            }

            /**
             * Sets the value of the ignoreCase property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setIgnoreCase(Boolean value) {
                this.ignoreCase = value;
            }

            /**
             * Gets the value of the initialValue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInitialValue() {
                return initialValue;
            }

            /**
             * Sets the value of the initialValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInitialValue(String value) {
                this.initialValue = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="backgroundImageBase64" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="gap" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="correct" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="inputLength">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *                       &lt;minInclusive value="1"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="ignoreCase" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                 &lt;attribute name="posX" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="posY" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="initialValue" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "backgroundImageBase64",
        "gap"
    })
    public static class GraphicalCloze {

        @XmlElement(required = true)
        protected String backgroundImageBase64;
        protected List<ClozeSubTaskDef.GraphicalCloze.Gap> gap;

        /**
         * Gets the value of the backgroundImageBase64 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBackgroundImageBase64() {
            return backgroundImageBase64;
        }

        /**
         * Sets the value of the backgroundImageBase64 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBackgroundImageBase64(String value) {
            this.backgroundImageBase64 = value;
        }

        /**
         * Gets the value of the gap property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the gap property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGap().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ClozeSubTaskDef.GraphicalCloze.Gap }
         * 
         * 
         */
        public List<ClozeSubTaskDef.GraphicalCloze.Gap> getGap() {
            if (gap == null) {
                gap = new ArrayList<ClozeSubTaskDef.GraphicalCloze.Gap>();
            }
            return this.gap;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="correct" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *       &lt;attribute name="inputLength">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
         *             &lt;minInclusive value="1"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="ignoreCase" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *       &lt;attribute name="posX" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="posY" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="initialValue" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "correct"
        })
        public static class Gap {

            @XmlElement(required = true)
            protected List<String> correct;
            @XmlAttribute
            protected Integer inputLength;
            @XmlAttribute
            protected Boolean ignoreCase;
            @XmlAttribute(required = true)
            protected int posX;
            @XmlAttribute(required = true)
            protected int posY;
            @XmlAttribute
            protected String initialValue;

            /**
             * Gets the value of the correct property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the correct property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCorrect().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getCorrect() {
                if (correct == null) {
                    correct = new ArrayList<String>();
                }
                return this.correct;
            }

            /**
             * Gets the value of the inputLength property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getInputLength() {
                return inputLength;
            }

            /**
             * Sets the value of the inputLength property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setInputLength(Integer value) {
                this.inputLength = value;
            }

            /**
             * Gets the value of the ignoreCase property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isIgnoreCase() {
                return ignoreCase;
            }

            /**
             * Sets the value of the ignoreCase property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setIgnoreCase(Boolean value) {
                this.ignoreCase = value;
            }

            /**
             * Gets the value of the posX property.
             * 
             */
            public int getPosX() {
                return posX;
            }

            /**
             * Sets the value of the posX property.
             * 
             */
            public void setPosX(int value) {
                this.posX = value;
            }

            /**
             * Gets the value of the posY property.
             * 
             */
            public int getPosY() {
                return posY;
            }

            /**
             * Sets the value of the posY property.
             * 
             */
            public void setPosY(int value) {
                this.posY = value;
            }

            /**
             * Gets the value of the initialValue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInitialValue() {
                return initialValue;
            }

            /**
             * Sets the value of the initialValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInitialValue(String value) {
                this.initialValue = value;
            }

        }

    }

}
