//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.28 at 10:41:44 AM MESZ 
//


package de.thorstenberger.taskmodel.complex.complextaskdef;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="pointsPerTask" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *             &lt;minInclusive value="0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="noOfSelectedTasks" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;minInclusive value="0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="preserveOrder" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "config")
public class Config {

    @XmlAttribute(required = true)
    protected float pointsPerTask;
    @XmlAttribute(required = true)
    protected int noOfSelectedTasks;
    @XmlAttribute(required = true)
    protected boolean preserveOrder;

    /**
     * Gets the value of the pointsPerTask property.
     * 
     */
    public float getPointsPerTask() {
        return pointsPerTask;
    }

    /**
     * Sets the value of the pointsPerTask property.
     * 
     */
    public void setPointsPerTask(float value) {
        this.pointsPerTask = value;
    }

    /**
     * Gets the value of the noOfSelectedTasks property.
     * 
     */
    public int getNoOfSelectedTasks() {
        return noOfSelectedTasks;
    }

    /**
     * Sets the value of the noOfSelectedTasks property.
     * 
     */
    public void setNoOfSelectedTasks(int value) {
        this.noOfSelectedTasks = value;
    }

    /**
     * Gets the value of the preserveOrder property.
     * 
     */
    public boolean isPreserveOrder() {
        return preserveOrder;
    }

    /**
     * Sets the value of the preserveOrder property.
     * 
     */
    public void setPreserveOrder(boolean value) {
        this.preserveOrder = value;
    }

}
