//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.28 at 10:41:44 AM MESZ 
//


package de.thorstenberger.taskmodel.complex.complextaskdef;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.thorstenberger.taskmodel.complex.complextaskdef package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.thorstenberger.taskmodel.complex.complextaskdef
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ComplexTaskDef.Revisions.Revision }
     * 
     */
    public ComplexTaskDef.Revisions.Revision createComplexTaskDefRevisionsRevision() {
        return new ComplexTaskDef.Revisions.Revision();
    }

    /**
     * Create an instance of {@link ClozeSubTaskDef.Cloze }
     * 
     */
    public ClozeSubTaskDef.Cloze createClozeSubTaskDefCloze() {
        return new ClozeSubTaskDef.Cloze();
    }

    /**
     * Create an instance of {@link Category.McTaskBlock }
     * 
     */
    public Category.McTaskBlock createCategoryMcTaskBlock() {
        return new Category.McTaskBlock();
    }

    /**
     * Create an instance of {@link Category.McTaskBlock.Choice }
     * 
     */
    public Category.McTaskBlock.Choice createCategoryMcTaskBlockChoice() {
        return new Category.McTaskBlock.Choice();
    }

    /**
     * Create an instance of {@link ComplexTaskDef.Config.CorrectionMode.CorrectOnlyProcessedTasks }
     * 
     */
    public ComplexTaskDef.Config.CorrectionMode.CorrectOnlyProcessedTasks createComplexTaskDefConfigCorrectionModeCorrectOnlyProcessedTasks() {
        return new ComplexTaskDef.Config.CorrectionMode.CorrectOnlyProcessedTasks();
    }

    /**
     * Create an instance of {@link Category.ClozeTaskBlock.Choice }
     * 
     */
    public Category.ClozeTaskBlock.Choice createCategoryClozeTaskBlockChoice() {
        return new Category.ClozeTaskBlock.Choice();
    }

    /**
     * Create an instance of {@link ComplexTaskDef.Config }
     * 
     */
    public ComplexTaskDef.Config createComplexTaskDefConfig() {
        return new ComplexTaskDef.Config();
    }

    /**
     * Create an instance of {@link Category.MappingTaskBlock }
     * 
     */
    public Category.MappingTaskBlock createCategoryMappingTaskBlock() {
        return new Category.MappingTaskBlock();
    }

    /**
     * Create an instance of {@link ClozeSubTaskDef.Cloze.Gap }
     * 
     */
    public ClozeSubTaskDef.Cloze.Gap createClozeSubTaskDefClozeGap() {
        return new ClozeSubTaskDef.Cloze.Gap();
    }

    /**
     * Create an instance of {@link Category.McTaskBlock.McConfig.Different }
     * 
     */
    public Category.McTaskBlock.McConfig.Different createCategoryMcTaskBlockMcConfigDifferent() {
        return new Category.McTaskBlock.McConfig.Different();
    }

    /**
     * Create an instance of {@link MappingSubTaskDef.Concept }
     * 
     */
    public MappingSubTaskDef.Concept createMappingSubTaskDefConcept() {
        return new MappingSubTaskDef.Concept();
    }

    /**
     * Create an instance of {@link Category.MappingTaskBlock.MappingConfig }
     * 
     */
    public Category.MappingTaskBlock.MappingConfig createCategoryMappingTaskBlockMappingConfig() {
        return new Category.MappingTaskBlock.MappingConfig();
    }

    /**
     * Create an instance of {@link ClozeSubTaskDef.GraphicalCloze }
     * 
     */
    public ClozeSubTaskDef.GraphicalCloze createClozeSubTaskDefGraphicalCloze() {
        return new ClozeSubTaskDef.GraphicalCloze();
    }

    /**
     * Create an instance of {@link de.thorstenberger.taskmodel.complex.complextaskdef.Config }
     * 
     */
    public de.thorstenberger.taskmodel.complex.complextaskdef.Config createConfig() {
        return new de.thorstenberger.taskmodel.complex.complextaskdef.Config();
    }

    /**
     * Create an instance of {@link ComplexTaskDef }
     * 
     */
    public ComplexTaskDef createComplexTaskDef() {
        return new ComplexTaskDef();
    }

    /**
     * Create an instance of {@link TextSubTaskDef }
     * 
     */
    public TextSubTaskDef createTextSubTaskDef() {
        return new TextSubTaskDef();
    }

    /**
     * Create an instance of {@link Category.TextTaskBlock.Choice }
     * 
     */
    public Category.TextTaskBlock.Choice createCategoryTextTaskBlockChoice() {
        return new Category.TextTaskBlock.Choice();
    }

    /**
     * Create an instance of {@link PaintSubTaskDef.Images }
     * 
     */
    public PaintSubTaskDef.Images createPaintSubTaskDefImages() {
        return new PaintSubTaskDef.Images();
    }

    /**
     * Create an instance of {@link ComplexTaskDef.Config.CorrectionMode.Regular }
     * 
     */
    public ComplexTaskDef.Config.CorrectionMode.Regular createComplexTaskDefConfigCorrectionModeRegular() {
        return new ComplexTaskDef.Config.CorrectionMode.Regular();
    }

    /**
     * Create an instance of {@link ComplexTaskDef.Revisions }
     * 
     */
    public ComplexTaskDef.Revisions createComplexTaskDefRevisions() {
        return new ComplexTaskDef.Revisions();
    }

    /**
     * Create an instance of {@link Category.PaintTaskBlock.Choice }
     * 
     */
    public Category.PaintTaskBlock.Choice createCategoryPaintTaskBlockChoice() {
        return new Category.PaintTaskBlock.Choice();
    }

    /**
     * Create an instance of {@link Category.AddonTaskBlock.Choice }
     * 
     */
    public Category.AddonTaskBlock.Choice createCategoryAddonTaskBlockChoice() {
        return new Category.AddonTaskBlock.Choice();
    }

    /**
     * Create an instance of {@link PaintSubTaskDef }
     * 
     */
    public PaintSubTaskDef createPaintSubTaskDef() {
        return new PaintSubTaskDef();
    }

    /**
     * Create an instance of {@link Category.McTaskBlock.McConfig.Regular }
     * 
     */
    public Category.McTaskBlock.McConfig.Regular createCategoryMcTaskBlockMcConfigRegular() {
        return new Category.McTaskBlock.McConfig.Regular();
    }

    /**
     * Create an instance of {@link McSubTaskDef.Incorrect }
     * 
     */
    public McSubTaskDef.Incorrect createMcSubTaskDefIncorrect() {
        return new McSubTaskDef.Incorrect();
    }

    /**
     * Create an instance of {@link McSubTaskDef.Correct }
     * 
     */
    public McSubTaskDef.Correct createMcSubTaskDefCorrect() {
        return new McSubTaskDef.Correct();
    }

    /**
     * Create an instance of {@link PaintSubTaskDef.TextualAnswer }
     * 
     */
    public PaintSubTaskDef.TextualAnswer createPaintSubTaskDefTextualAnswer() {
        return new PaintSubTaskDef.TextualAnswer();
    }

    /**
     * Create an instance of {@link ComplexTaskDef.Config.CorrectionMode }
     * 
     */
    public ComplexTaskDef.Config.CorrectionMode createComplexTaskDefConfigCorrectionMode() {
        return new ComplexTaskDef.Config.CorrectionMode();
    }

    /**
     * Create an instance of {@link ComplexTaskDef.Config.CorrectionMode.MultipleCorrectors }
     * 
     */
    public ComplexTaskDef.Config.CorrectionMode.MultipleCorrectors createComplexTaskDefConfigCorrectionModeMultipleCorrectors() {
        return new ComplexTaskDef.Config.CorrectionMode.MultipleCorrectors();
    }

    /**
     * Create an instance of {@link ClozeSubTaskDef.GraphicalCloze.Gap }
     * 
     */
    public ClozeSubTaskDef.GraphicalCloze.Gap createClozeSubTaskDefGraphicalClozeGap() {
        return new ClozeSubTaskDef.GraphicalCloze.Gap();
    }

    /**
     * Create an instance of {@link Category.AddonTaskBlock }
     * 
     */
    public Category.AddonTaskBlock createCategoryAddonTaskBlock() {
        return new Category.AddonTaskBlock();
    }

    /**
     * Create an instance of {@link Category.MappingTaskBlock.Choice }
     * 
     */
    public Category.MappingTaskBlock.Choice createCategoryMappingTaskBlockChoice() {
        return new Category.MappingTaskBlock.Choice();
    }

    /**
     * Create an instance of {@link Category.TextTaskBlock }
     * 
     */
    public Category.TextTaskBlock createCategoryTextTaskBlock() {
        return new Category.TextTaskBlock();
    }

    /**
     * Create an instance of {@link MappingSubTaskDef.Assignment }
     * 
     */
    public MappingSubTaskDef.Assignment createMappingSubTaskDefAssignment() {
        return new MappingSubTaskDef.Assignment();
    }

    /**
     * Create an instance of {@link MappingSubTaskDef }
     * 
     */
    public MappingSubTaskDef createMappingSubTaskDef() {
        return new MappingSubTaskDef();
    }

    /**
     * Create an instance of {@link Category.PaintTaskBlock }
     * 
     */
    public Category.PaintTaskBlock createCategoryPaintTaskBlock() {
        return new Category.PaintTaskBlock();
    }

    /**
     * Create an instance of {@link ClozeSubTaskDef }
     * 
     */
    public ClozeSubTaskDef createClozeSubTaskDef() {
        return new ClozeSubTaskDef();
    }

    /**
     * Create an instance of {@link Category.McTaskBlock.McConfig }
     * 
     */
    public Category.McTaskBlock.McConfig createCategoryMcTaskBlockMcConfig() {
        return new Category.McTaskBlock.McConfig();
    }

    /**
     * Create an instance of {@link McSubTaskDef }
     * 
     */
    public McSubTaskDef createMcSubTaskDef() {
        return new McSubTaskDef();
    }

    /**
     * Create an instance of {@link Category.ClozeTaskBlock.ClozeConfig }
     * 
     */
    public Category.ClozeTaskBlock.ClozeConfig createCategoryClozeTaskBlockClozeConfig() {
        return new Category.ClozeTaskBlock.ClozeConfig();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link AddonSubTaskDef }
     * 
     */
    public AddonSubTaskDef createAddonSubTaskDef() {
        return new AddonSubTaskDef();
    }

    /**
     * Create an instance of {@link Category.ClozeTaskBlock }
     * 
     */
    public Category.ClozeTaskBlock createCategoryClozeTaskBlock() {
        return new Category.ClozeTaskBlock();
    }

}
